baseURL = "https://charliehowlett.co.uk/"
languageCode = "en-gb"
title = "Charlie Howlett"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[module]
  [[module.imports]]
    path = "github.com/mrchazaaa/hugo-teletext"

[params]
  enableScanlines = false
  pageNumber = "100"
